# Generated by Selenium IDE
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class syscoinBot():
    def quit(self):
        self.driver.quit()
  
    def mine(self):
        '''host = "127.0.0.1"
        port = "9150"
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument("--proxy-server=socks5://" + host + ":" + port)
        self.driver = webdriver.Chrome(chrome_options=chrome_options)'''
        chrome_options = webdriver.ChromeOptions()
        chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--no-sandbox")
        self.driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)
        self.driver.get("https://faucet.syscoin.org/")
        '''if "faucet.syscoin.org" in self.driver.title:
            self.quit()
        else:'''
        print("Connecté !")
        self.driver.find_element(By.ID, "address").click()
        self.driver.find_element(By.ID, "address").send_keys("sys1qvuncdxpaavf0zu7m96zsr87fsvpnm4zxvpq482")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

    def already_mined(self):
        if self.driver.current_url != "https://faucet.syscoin.org/mine":
            print("IP déjà utilisée !")
            self.quit()
            return True
        else:
            while (self.driver.current_url == "https://faucet.syscoin.org/mine"):
                pass
            print("Minage réussi !")
            self.driver.implicitly_wait(3)
            if (self.driver.current_url != "https://faucet.syscoin.org/mine"):
                return False
                self.quit()

    def random_line(self):
        text = None
        os.chdir(r'C:\Users\mkel\Downloads\syscoin\selenium')
        for line in fileinput.input('proxy.txt'):
            if random.randrange(fileinput.lineno()) == 0:
                text = line
        return text